import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, FileText, MessageCircle } from 'lucide-react';
import { PAYMENT_TERMS } from '@/data/content';
import { openManagerTelegram } from '@/lib/utils';
import LeadForm from '@/components/LeadForm';

export default function BusinessPage() {
  return <div className="pt-20">
    <section className="relative py-16 sm:py-24 overflow-hidden"><div className="absolute inset-0 hero-mesh" /><div className="content-layer max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-[1.1fr_.9fr] gap-10 items-center"><div><span className="inline-flex glass-orange px-4 py-2 rounded-full text-sm font-semibold text-brand-700 mb-5">Для бизнеса</span><h1 className="font-display font-extrabold text-4xl sm:text-5xl text-gray-900 leading-tight mb-5">Оплата китайских поставщиков по инвойсу</h1><p className="text-lg text-gray-600 leading-relaxed mb-7">Передайте реквизиты или инвойс, получите расчёт в рублях и согласуйте перевод поставщику с менеджером.</p><div className="flex flex-col sm:flex-row gap-3"><Link to="/contacts#lead-form" className="btn-primary">Получить расчёт <ArrowRight className="w-5 h-5" /></Link><button onClick={openManagerTelegram} className="btn-glass"><MessageCircle className="w-5 h-5 text-brand-500" /> Написать менеджеру</button></div></div><div className="glass-card p-6 sm:p-8"><LeadForm business title="Рассчитать платёж по инвойсу" /></div></div></div></section>
    <section className="py-14 bg-brand-50/40"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="font-display font-bold text-3xl text-center mb-10">Как проходит заявка</h2><div className="grid md:grid-cols-4 gap-5">{[['01','Инвойс','Присылаете сумму, валюту и реквизиты.'],['02','Расчёт','Менеджер подтверждает курс, комиссию и срок.'],['03','Оплата','Переводите согласованную сумму по реквизитам.'],['04','Перевод','Получаете подтверждение отправки поставщику.']].map(([number,title,text]) => <div key={number} className="glass-card p-5"><div className="text-brand-600 font-display font-extrabold text-xl mb-3">{number}</div><h3 className="font-display font-bold text-lg mb-2">{title}</h3><p className="text-sm text-gray-600">{text}</p></div>)}</div></div></section>
    <section className="py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 grid md:grid-cols-2 gap-8"><div><h2 className="font-display font-bold text-3xl mb-5">Что уточним заранее</h2><ul className="space-y-4">{['Сумму и валюту инвойса','Реквизиты китайского получателя','Комиссию и итог к оплате',PAYMENT_TERMS.timing].map((item) => <li key={item} className="flex gap-3 text-gray-700"><CheckCircle2 className="w-5 h-5 text-brand-600 shrink-0" />{item}</li>)}</ul></div><div className="glass-card p-7"><FileText className="w-8 h-8 text-brand-600 mb-4" /><h2 className="font-display font-bold text-2xl mb-3">Инвойс можно прислать менеджеру</h2><p className="text-gray-600 mb-5">Для безопасности загрузка файла на сайте не используется. Отправьте документ в Telegram после согласования заявки.</p><button onClick={openManagerTelegram} className="btn-primary">Открыть Telegram</button></div></div></section>
  </div>;
}
