import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Calculator, CheckCircle2, MessageCircle, RefreshCw, Send, Wallet } from 'lucide-react';
import { PAYMENT_TERMS } from '@/data/content';
import { formatNumber, openClientChatTelegram, openManagerTelegram } from '@/lib/utils';
import CTASection from '@/components/CTASection';

type Rates = { buyRate: number; sellRate: number };

export default function HomePage() {
  const [rates, setRates] = useState<Rates | null>(null);
  useEffect(() => { fetch('/api/rates').then((r) => r.ok ? r.json() : Promise.reject()).then(setRates).catch(() => setRates(null)); }, []);
  return <div className="pt-20">
    <section className="relative overflow-hidden"><picture className="absolute inset-0"><source media="(max-width: 767px)" srcSet="/assets/hero-moile-back.png" /><img src="/assets/hero-back.png" alt="" className="w-full h-full object-cover" /></picture><div className="absolute inset-0 bg-white/80" /><div className="absolute inset-0 hero-mesh" /><div className="content-layer max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24"><div className="grid lg:grid-cols-[1.05fr_.95fr] gap-10 items-center"><div><span className="inline-flex glass-orange px-4 py-2 rounded-full text-sm font-semibold text-brand-700 mb-5">FTS-Pay</span><h1 className="font-display font-extrabold text-4xl sm:text-5xl lg:text-6xl text-gray-900 leading-tight mb-5">Оплата покупок в Китае и пополнение Alipay / WeChat</h1><p className="text-lg text-gray-600 leading-relaxed mb-7 max-w-2xl">Поможем оплатить китайскому продавцу или пополнить кошелёк в юанях. Рассчитайте платёж и узнайте курс, комиссию и итоговую сумму до оплаты.</p><div className="flex flex-col sm:flex-row gap-3"><Link to="/calculator" className="btn-primary text-base px-6 py-4"><Calculator className="w-5 h-5" /> Рассчитать платёж</Link><button onClick={openManagerTelegram} className="btn-glass text-base px-6 py-4"><MessageCircle className="w-5 h-5 text-brand-500" /> Написать менеджеру</button></div><button onClick={openClientChatTelegram} className="btn-telegram mt-4 w-full sm:w-auto text-base px-6 py-3.5"><Send className="w-5 h-5 shrink-0" /><span className="text-left"><span className="block">Чат клиентов в Telegram</span><span className="block text-xs font-medium text-white/80">Отзывы, опыт и вопросы клиентов</span></span><ArrowRight className="w-4 h-4 ml-1" /></button></div><div className="glass-card p-6 sm:p-8"><div className="flex items-center justify-between mb-5"><div><div className="text-sm text-gray-500">Предварительный курс</div><div className="text-3xl font-display font-extrabold text-brand-600">{rates ? `1 CNY = ${formatNumber(rates.buyRate, 4)} RUB` : 'Уточняется менеджером'}</div></div><RefreshCw className="w-7 h-7 text-brand-500" /></div><div className="space-y-3 mb-5"><div className="flex justify-between text-sm"><span>Комиссия</span><strong>{PAYMENT_TERMS.commissionPercent}% сверху</strong></div><div className="flex justify-between text-sm"><span>Минимум</span><strong>{PAYMENT_TERMS.minimumCny.toLocaleString('ru-RU')} CNY / {PAYMENT_TERMS.minimumRub.toLocaleString('ru-RU')} ₽</strong></div><div className="flex justify-between text-sm"><span>Ориентир</span><strong>{PAYMENT_TERMS.indicativeRange}</strong></div></div><Link to="/calculator" className="btn-primary w-full"><Calculator className="w-5 h-5" /> Рассчитать платёж</Link><p className="text-xs text-gray-500 mt-3">{PAYMENT_TERMS.rateNote}</p></div></div></div></section>
    <section className="py-14"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid md:grid-cols-2 gap-6"><Link to="/for-you" className="glass-card p-7 group"><Wallet className="w-8 h-8 text-brand-600 mb-4" /><h2 className="font-display font-bold text-2xl mb-2">Для себя</h2><p className="text-gray-600 mb-4">Alipay, WeChat Pay или оплата китайскому продавцу для личной покупки.</p><span className="text-brand-600 font-semibold inline-flex items-center gap-2">Подробнее <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" /></span></Link><Link to="/business" className="glass-card p-7 group"><CheckCircle2 className="w-8 h-8 text-brand-600 mb-4" /><h2 className="font-display font-bold text-2xl mb-2">Для бизнеса</h2><p className="text-gray-600 mb-4">Оплата поставщикам по инвойсу с расчётом суммы и подтверждением до оплаты.</p><span className="text-brand-600 font-semibold inline-flex items-center gap-2">Подробнее <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" /></span></Link></div></div></section>
    <section className="py-16 bg-brand-50/40"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="font-display font-bold text-3xl text-center mb-10">Как проходит платёж</h2><div className="grid md:grid-cols-4 gap-5">{['Заявка и сумма','Расчёт курса и комиссии','Подтверждение до оплаты','Перевод получателю'].map((title, index) => <div key={title} className="glass-card p-5"><div className="text-brand-600 font-display font-extrabold text-xl mb-3">0{index + 1}</div><h3 className="font-display font-bold text-lg mb-2">{title}</h3><p className="text-sm text-gray-600">{index === 0 ? 'Оставляете заявку на сайте или пишете менеджеру.' : index === 1 ? 'Менеджер уточняет актуальный курс и итог.' : index === 2 ? 'Срок перевода подтверждаем с менеджером до оплаты.' : 'После оплаты отправляем юани и подтверждение.'}</p></div>)}</div></div></section>
    <CTASection title="Нужен расчёт платежа?" subtitle="Оставьте сумму или напишите менеджеру. Курс и условия подтверждаем до оплаты." />
  </div>;
}
